LIFETIME_SECONDS: int = 3600
NAME_MAX_LENGHT: int = 100
NAME_MIN_LENGHT: int = 1
DESCRIPTION_MIN_LENGHT: int = 1
DEFAULT_INVESTED_AMOUNT: int = 0
PASSWORD_MIN_LENGHT: int = 3
DATETIME_FORMAT_FOR_GOOGLE_SHEET: str = '%Y/%m/%d %H:%M:%S'
MAX_INVESTED_AMOUNT: int = 0
